server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lsd2016/itzixishi # 配置git仓库的地址
          search-paths: itzixishi-admin/config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 1157718866@qq.com # git仓库的账号（私有库必填）
          password: lsd19860713 # git仓库的密码（私有库必填）
      label: master #配置git仓库的分支